"""empty message

Revision ID: 6c3a578f4879
Revises: 020fbd508ade
Create Date: 2025-10-20 20:16:21.887556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c3a578f4879'
down_revision = '020fbd508ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               nullable=True)

    # ### end Alembic commands ###
