"""empty message

Revision ID: 925fcebfb39d
Revises: 6c3a578f4879
Create Date: 2025-10-20 20:21:58.550839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '925fcebfb39d'
down_revision = '6c3a578f4879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('total_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###
